### ISSUE TITLE
Ĉu neniuj kompreneblaj instrukcioj pri kiel munti la vortaron?

### ISSUE THREAD

**Issue by keithbowes** [revuloj/revo-fonto#26]
Pro la novjaro mi ĵus elŝutis la novan eldonon de ReVo sed rimarkis la aĉan formaton, do mi volis reakiri malnovan eldonon, sed mi povis trovi ĝin nur laŭ la fontoteksta formo. Mi konscias ke mi stultas, sed mi ne povas kompreni kiel munti ĝin (konverti la XML-dosierojn al HTML).

La vikia paĝo pri "diurna aktualigo" estas tre konfuza.

> Eltrovi la pozicion (sha_nf) de la marko nokta-formiko (git tag) kaj per voko-formiko krei la kadrajn dosierojn kaj ĉiujn indeksojn de la vortaro

Ĉu? Per `git tag` en voko-formiko estas neniu nokta-formiko:
```
$ GIT_PAGER=cat git tag
stabila
v2020-02-23
v2020-04-01
```

Ĉu tio indikas, ke oni devas enmeti la dosierojn de voko-formiko en la sha_nf subdosierujo de revo-fonto? Ĉu io alia?

> krei la kadrajn kaj indeksajn dosierojn
Kiel? Ĉu mi devus permane skribi la HTML-dosierojn?

> krei dosieron .reftempo kun la nuna tempo
Kiel? `date > .reftempo`? Ĉu la data formato gravas?

Tio estas nur la unua paŝo kaj mi jam estas funde konfuzita.

**Comment by wdiestel** [comment]
Mi ankoraŭ ne certas pri kio vi plendas kaj kion ekzakte vi volas fari. Ĉu temas pri la nova fasado? Kion vi celas per "aĉa formato" do?

- bv. plendi pli konkrete, por ke en sekvaj versioj mi povos espereble plibonigi, kio vin ĝenas. 
- se temas pri la nova fasado subtenanta poŝtelefonajn ekranojn, vi povas plu uzi la malnovan fasadon per la enirpaĝo: http://www.reta-vortaro.de/revo/index-malnova.html
- bonvolu indiki kiun retumilon en kiu sistemo (inkl. versioj) vi uzas. Prefere vi uzu retumilan version postprintempan de 2020.

# Konstrui propran lokan vortaron

Tio ne estas tute triviala, ĉar ĝi konsistas el pluraj partoj kaj ĝis nun mi ne scias pri iu uzanto, kiu regule kreas propran lokan vortaron (ekster la apoj PoŝRevo / PRevo). Mi fokusas mian limigitan liberan tempon al tio, kio supozeble utilos al la plimulto de la uzantoj, sed kun iom da ambicio kaj helpo vi povus kunuzi la aranĝaĵon, kiun mi uzas por testado: Verŝajne vi volas havi la serĉilon kune kun la retpaĝoj. 

La nurajn retpaĝojn vi povas elŝuti el la [ĉiutaga eldono](https://github.com/revuloj/revo-fonto/releases/). Plej simple per la skripto: [voko-araneo/bin/revo_donwload_gh.sh](https://github.com/revuloj/voko-araneo/blob/master/bin/revo_download_gh.sh)

Se vi volas loke ruli la retpaĝojn kun la serĉdatumbazo, la plej rekta voko verŝajne estas instali `docker swarm` en via komputilo kaj uzi la skripton [revo-medioj/araneujo/docker-compose.yml](https://github.com/revuloj/revo-medioj/blob/master/araneujo/docker-compose.yml). Prefere elĵetu tie "tomocero"- la retpoŝtservon, se vi ne volas redakti, kaj "sesio" - la ftp-servilon. Sufiĉas "araneo" - la http-servo kaj "abelo" - la datumbazo.

Antaŭe vi devos prepari vian medio per la skriptoj en `revo-medioj/bin` kaj krei kelkajn sekretojn per la dosieroj `revo-medioj/araneujo*ŝablono`

**Comment by wdiestel** [comment]
Ne venis detaloj pri la helpopeto. Mi aldonis informojn al vikipaghoj, ke ili koncernas administradon por estimpli klara. Do mi fermas la avizon.

**Comment by keithbowes** [comment]
> Ne venis detaloj pri la helpopeto.

Vi ne donis al mi sufiĉon da tempo por akiri la kuraĝon legi la respondojn. Nun mia koro rapide batadas, mi ŝvitas kaj mi sentas kvazaŭ mi estas svenonta, kaj mi ne eĉ legis la longan respondon. Mi supozas ke mi forlasos la deziron atingi malnovan version.

Ne nur vi. Mia GitHub-mesaĝujo havas paĝojn da mesaĝoj kaj mi ne certas, kiun mi bezonas legi, sed estas malfacilege.

**Comment by wdiestel** [comment]
Prenu la tempon kiun vi bezonas, mi ne urĝas vin. Se estas pli klare, kion vi volas fari kaj kian helpon vi atendas, simple reskribu tie ĉi. Mi ankoraŭ ne komprenis, kial vi bezonas malnovan version.
