### ISSUE TITLE
Permesilo de la datumaro

### ISSUE THREAD

**Issue by bpeel** [revuloj/revo-fonto#47]
Ĉu eblus aldoni permesilon al la deponejo, same kiel oni faris por [Voko-Grundo](https://github.com/revuloj/voko-grundo/blob/master/LICENSE)?

Mi demandas ĉar mi volas fari novan version de PReVo en F-Droid (deponejo de liberprogramaj aplikaĵoj por Android), kaj mi volas rekte uzi ĉi tiun deponejon anstataŭ la antaŭa solvi kopii la zip-ojn de la retejo. Kiam mi provis aldoni la deponejon iu [atentigis](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10829#note_896864292) ke ĝi ne havas permesilon kaj ja ne estas klare laŭ kiu permesilo ni rajtas uzi la datumojn.

**Comment by wdiestel** [comment]
Saluton Neil,

la retpagho de Revo informas pri permesilo GPL 2. Sed mi povos okaze ankau inkluzivi ghin rekte en la deponejo. 

Amike,
Wolfram.
